version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chart.js
    versions:
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: ember-cli
    versions:
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.26.0
    - 3.26.1
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.2.0
    - 10.3.0
    - 10.4.1
  - dependency-name: broccoli-funnel
    versions:
    - 3.0.4
  - dependency-name: qunit
    versions:
    - 2.15.0
  - dependency-name: acorn
    versions:
    - 8.1.1
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: ember-cli-babel
    versions:
    - 7.25.0
    - 7.26.1
    - 7.26.2
    - 7.26.3
  - dependency-name: ember-data
    versions:
    - 3.26.0
  - dependency-name: ember-source
    versions:
    - 3.25.0
    - 3.25.1
    - 3.25.3
    - 3.26.0
    - 3.26.1
  - dependency-name: "@ember/test-helpers"
    versions:
    - 2.2.5
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.2
    - 5.5.0
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
    - 5.7.1
  - dependency-name: ember-concurrency
    versions:
    - 2.0.0
    - 2.0.3
  - dependency-name: ember-qunit
    versions:
    - 5.1.2
    - 5.1.3
    - 5.1.4
  - dependency-name: ember-cli-app-version
    versions:
    - 5.0.0
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
    - 10.2.5
  - dependency-name: postcss-scss
    versions:
    - 3.0.5
  - dependency-name: pace-js
    versions:
    - 1.2.3
    - 1.2.4
  - dependency-name: jquery
    versions:
    - 3.6.0
  - dependency-name: moment-timezone
    versions:
    - 0.5.33
